#!/bin/bash
if [[ ! -f "data/www/angular.js" ]]; then
    curl https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.js -o data/www/angular.js
fi
wordwang_datadir=data ./dist/build/wordwang-server/wordwang-server "$@"
